name: ECCFP
channels:
  - bioconda
  - conda-forge
dependencies:
  - biopython=1.85
  - numpy=1.26.4
  - pandas=2.3.2
  - pyfaidx=0.9.0.1
  - pyfastx=2.2.0
  - python=3.12.11
  - rich=14.1.0
  - minimap2=2.30
