name: Weekly Traffic Data Collection

on:
  schedule:
    - cron: '0 3 * * 1'  # 每周一UTC时间3:00运行
  workflow_dispatch:

jobs:
  traffic:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      with:
        ref: 'traffic-data'

    - name: Install jq  # 新增jq安装
      run: sudo apt-get install -y jq

    - name: Get traffic data
      uses: WSG-Lab/ECCFP@main
      id: traffic
      with:
        format: 'json'

    - name: Process and save monthly data
      run: |
        mkdir -p traffic-data
        MONTH=$(date -u +"%Y-%m")
        FILE="traffic-data/$MONTH.json"
        DATA='${{ steps.traffic.outputs.data }}'
        JSON_DATA=$(echo "$DATA" | jq -c .)
        
        if [ ! -f "$FILE" ]; then
          echo '{"weeks":{}}' > "$FILE"
        fi
        
        WEEK_START=$(date -u -d "last monday" +"%Y-%m-%d")
        
        jq --arg week "$WEEK_START" \
           --argjson newData "$JSON_DATA" \
           '.weeks[$week] = $newData' \
           "$FILE" > tmp.json && mv tmp.json "$FILE"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@users.noreply.github.com"
        git add traffic-data/
        git commit -m "Weekly traffic update for $(date -u +'%Y-%m-%d')"
        git push
